name: Unit Test on Pull Request

on:
  pull_request:
    branches: [main]

jobs:
  unit_job:
    name: Job for Unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "16"
      - run: npm ci
      - run: echo "Running unit test"
      - run: npm test
